services:
  postgres:
    ports: []

  redis:
    ports: []

  backend:
    env_file:
      - ./backend/.env.production
    # Запускаем через твой скрипт, чтобы уровни копировались и база ждалась
    command: ["/bin/bash", "/app/entrypoint.prod.sh"]
    volumes:
      # Прокидываем постоянную папку с сервера внутрь контейнера
      - /srv/arrows/levels:/app/app/levels
    ports: []

  bot:
    env_file:
      - ./backend/.env.production
    volumes: []