version: '3.8'

services:
  backend:
    env_file:
      - ./backend/.env.production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes: []

  bot:
    env_file:
      - ./backend/.env.production
    volumes: []
